---
swagger: '2.0'
info:
  description: Payment Processor Billing System
  version: '1.1'
  title: Payment Processor Billing System
host: localhost:8080
basePath: "/"
tags:
- name: basic-error-controller
  description: Basic Error Controller
- name: index-controller
  description: Index Controller
paths:

#Ecommerce API
  "/ecommerce/{id}":
    get:
      tags:
      - ecommerce
      summary: Get ecommerce detail
      operationId: getEcommerce
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer      
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceDetail"
        '204':
          description: No Content            
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  
    delete:
      tags:
      - ecommerce
      summary: Delete Ecommmerce
      operationId: deleteEcommerce
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceDetail"          
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
      
    put:
      tags:
      - ecommerce
      summary: Update ecommerce
      operationId: updateEcommerce
      consumes:
      - application/json
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer      
      - name: body
        in: body
        description: Body request
        required: true
        schema: 
            $ref: "#/definitions/Ecommerce"            
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceDetail"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false            

  "/ecommerce":
    post:
      tags:
      - ecommerce
      summary: Create new ecommerce
      operationId: createEcommerce
      consumes:
      - application/json
      produces:
      - "application/json"
      parameters:
      - name: body
        in: body
        description: Body request
        required: true
        schema: 
            $ref: "#/definitions/Ecommerce"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceDetail"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    
    get:
      tags:
      - ecommerce
      summary: Get all ecommerce 
      operationId: getAllEcommerce
      produces:
      - "application/json"  
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
                "$ref": "#/definitions/EcommerceDetail"
        '204':
          description: No Content            
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false      


  "/ecommerce/{id}/report/{year}/{month}":
    get:
      tags:
      - ecommerce
      summary: Report monthly settlement Ecommerce
      operationId: reportEcommerce
      consumes:
      - application/json
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
      - name: year
        in: path
        required: true
        type: integer        
      - name: month
        in: path
        required: true
        type: integer
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceReport"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false    
      
  "/ecommerce/{id}/payment":
    post:
      tags:
      - ecommerce
      summary: Create new payment link to the ecommerce
      operationId: createPayment
      consumes:
      - application/json
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: id ecommerce
        required: true
        type: integer      
      - name: body
        in: body
        description: Body request
        required: true
        schema: 
            $ref: "#/definitions/Payment"
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false      

 #Payment Processor API
  "/paymentprocessor/{id}":
    get:
      tags:
      - Payment Processor
      summary: Get Payment Processor detail
      operationId: getPaymentProcessor
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer      
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/PaymentProcessorDetail"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  
    delete:
      tags:
      - Payment Processor
      summary: Delete Payment Processor
      operationId: deletePaymentProcessor
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/PaymentProcessorDetail"
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
      
    put:
      tags:
      - Payment Processor
      summary: Update Payment Processor
      operationId: updatePaymentProcessor
      consumes:
      - application/json
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer      
      - name: body
        in: body
        description: Body request
        required: true
        schema: 
            $ref: "#/definitions/PaymentProcessor"
            
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/PaymentProcessorDetail"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false            

  "/paymentprocessor":
    post:
      tags:
      - Payment Processor
      summary: create new payment processor
      operationId: createPaymentProcessor
      consumes:
      - application/json
      produces:
      - "application/json"
      parameters:
      - name: body
        in: body
        description: Body request
        required: true
        schema: 
            $ref: "#/definitions/PaymentProcessor"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/PaymentProcessorDetail"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false


  "/paymentprocessor/{id}/report":
    get:
      tags:
      - Payment Processor
      summary: Report monthly 
      operationId: reportPaymentProcessor
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/PaymentProcessorReport"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false          

definitions:
  Ecommerce:
    type: object
    title: Ecommerce
    description: This is ecommerce model      
    required:
    - name
    properties:
      name:
        type: string
        description: Ecommerce name
      idPaymentProcessor:
        type: integer
        description: Payment Processor
        
    
  EcommerceDetail:
    type: object
    title: Ecommerce
    description: This is ecommerce model    
    required:
    - name
    properties:
      id:
        type: integer
        description: Ecommerce Id    
      name:
        type: string
        description: Ecommerce name      
      idPaymentProcessor:
        type: integer
        description: Payment Processor        

    
  EcommerceReport:
    type: object
    properties:
      ecommerceName:
        type: string
        description: Ecommerce name
      month:
        type: string
        description: Month
      paymentProcessorName:
        type: string
        description: Payment Processor name  
      listTransactions:
        type: array
        items: 
            $ref: "#/definitions/Transactions"                
    title: View
    
  Transactions:
    type: object
    title: Payment Processor
    description: This is Payment Processor model    
    required:
    - name
    properties:      
      day:
        type: string
        description: Day of month    
      transactions:
        type: integer
        description: Number transactions
      amount:
        type: number
        format: double
        description: Total amount + tax
 

  PaymentProcessor:
    type: object
    title: Payment Processor
    description: This is Payment Processor model    
    required:
    - name
    properties:      
      name:
        type: string
        description: Payment Processor name        
      flatfee:
        type: number
        format: float
        description: Commission for each transaction      
      listAPP:
        type: array
        items: 
            $ref: "#/definitions/APP"

  PaymentProcessorDetail:
    type: object
    title: Payment Processor
    description: This is Payment Processor model    
    required:
    - name
    properties:
      id:
        type: integer
        description: Payment procesor Id    
      name:
        type: string
        description: Payment Processor name        
      flatfee:
        type: number
        format: float
        description: Commission for each transaction  
      listAPP:
        type: array
        items: 
            $ref: "#/definitions/APP"        

  APP:
    type: object
    title: Payment Processor
    description: This is Payment Processor model    
    properties:
      volumen:
        type: integer        
        description: Volumen   
      app:
        type: number
        format: float
        description: app value       

  Payment:
    type: object
    title: Payment 
    description: This is Payment model    
    properties:
      amount:
        type: number
        format: double
        description: Payment amount
      date:
        type: string
        format: date
        description: Payment amount
        required: true
      description:
        type: string
        description: Payment description

  PaymentProcessorReport:
    type: object
    title: Payment Processor Report
    description: This is Payment Processor Report 
    properties:
      paymentProcessorName:
        type: string        
        description: Payment processor name
      listEcommerce:
        type: array
        items: 
            $ref: "#/definitions/EcommerceBilling" 

  EcommerceBilling:
    type: object
    title: EcommerceBilling 
    description: This is EcommerceBilling model    
    properties:
      ecommerceName:
        type: string
        description: Ecommerce name
      amount:
        type: number
        format: double
        description: Payment description            
