---
swagger: '2.0'
info:
  description: Payment Processor Billing System
  version: '1.1'
  title: Payment Processor Billing System
host: localhost:8080
basePath: "/"
tags:
- name: basic-error-controller
  description: Basic Error Controller
- name: index-controller
  description: Index Controller
paths:

#Ecommerce API
  "/ecommerce/{id}":
    get:
      tags:
      - ecommerce
      summary: Get ecommerce detail
      operationId: getEcommerce
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceDetail"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  
    delete:
      tags:
      - ecommerce
      summary: Delete Ecommmerce
      operationId: deleteEcommerce
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceDetail"
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
      
    put:
      tags:
      - ecommerce
      summary: Update ecommerce
      operationId: updateEcommerce
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: body
        in: body
        description: Body request
        required: true
        schema: 
            $ref: "#/definitions/Ecommerce"
            
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceDetail"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false            

  "/ecommerce":
    post:
      tags:
      - ecommerce
      summary: create new ecommerce
      operationId: createEcommerce
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: body
        in: body
        description: Body request
        required: true
        schema: 
            $ref: "#/definitions/Ecommerce"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceDetail"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false


  "/ecommerce/{id}/report/{month}":
    get:
      tags:
      - ecommerce
      summary: Report monthly settlement Ecommerce
      operationId: reportEcommerce
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
      - name: month
        in: path
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceReport"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false    

 #Payment Processor API
  "/paymentprocessor/{id}":
    get:
      tags:
      - Payment Processor
      summary: Get Payment Processor detail
      operationId: getPaymentProcessor
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/PaymentProcessorDetail"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  
    delete:
      tags:
      - Payment Processor
      summary: Delete Payment Processor
      operationId: deletePaymentProcessor
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/PaymentProcessorDetail"
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
      
    put:
      tags:
      - Payment Processor
      summary: Update Payment Processor
      operationId: updatePaymentProcessor
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: body
        in: body
        description: Body request
        required: true
        schema: 
            $ref: "#/definitions/PaymentProcessor"
            
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/PaymentProcessorDetail"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false            

  "/paymentprocessor":
    post:
      tags:
      - Payment Processor
      summary: create new payment processor
      operationId: createPaymentProcessor
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: body
        in: body
        description: Body request
        required: true
        schema: 
            $ref: "#/definitions/PaymentProcessor"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/PaymentProcessorDetail"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false


  "/paymentprocessor/{id}/report":
    get:
      tags:
      - Payment Processor
      summary: Report monthly 
      operationId: reportPaymentProcessor
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/EcommerceReport"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false          

definitions:
  Ecommerce:
    type: object
    title: Ecommerce
    description: This is ecommerce model      
    required:
    - name
    properties:
      name:
        type: string
        description: Ecommerce name
    
  EcommerceDetail:
    type: object
    title: Ecommerce
    description: This is ecommerce model    
    required:
    - name
    properties:
      id:
        type: string
        description: Ecommerce Id    
      name:
        type: string
        description: Ecommerce name      
    
  EcommerceReport:
    type: object
    properties:
      ecommerceName:
        type: string
        description: Ecommerce name
      month:
        type: string
        description: Month
      paymentProcessorName:
        type: string
        description: Payment Processor name        
    title: View

  PaymentProcessor:
    type: object
    title: Payment Processor
    description: This is Payment Processor model    
    required:
    - name
    properties:      
      name:
        type: string
        description: Payment Processor name        
      flatfee:
        type: string
        description: Commission for each transaction      
      listAPP:
        type: array
        items: 
            $ref: "#/definitions/APP"

  PaymentProcessorDetail:
    type: object
    title: Payment Processor
    description: This is Payment Processor model    
    required:
    - name
    properties:
      id:
        type: string
        description: Payment procesor Id    
      name:
        type: string
        description: Payment Processor name        
      flatfee:
        type: string
        description: Commission for each transaction       

  APP:
    type: object
    title: Payment Processor
    description: This is Payment Processor model    
    properties:
      volumen:
        type: string
        description: Payment procesor Id    
      app:
        type: string
        description: Payment Processor name        
